### ISSUE TITLE
Shadow under pullers no longer change size

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#17]
It looks like the shadows under pullers no longer change size when the force changes.  Here is GFL master:
![pull2](https://user-images.githubusercontent.com/6396244/29795614-30f231c2-8c0a-11e7-8f75-23c7e9b52ca9.PNG)

and deployed version:
![pull](https://user-images.githubusercontent.com/6396244/29795617-36832592-8c0a-11e7-8e5f-137fd2341907.PNG)

(The rope length is a separate issue, specific to GFL).

**Comment by mbarlow12** [comment]
The trouble here is that the deployed version has changing image widths for the pullers, and the Path node for the shadow can be scaled accordingly.  Since the new puller images don't have that value, we'd need to find another method to expand and contract the shadow.

The only other value that changes with the images is the index as we loop over them. So there may be a way to create varying sizes in this way. This brings up 2 issues: 1) if the necessary change in shadow size isn't linear then the shadow won't really align with the puller and 2) we'll likely run into trouble with CL where the size of the array is doubled and the pusher images also have varying widths.

The other option is to request yet another full redesign for the pullers and pushers after a full discussion of what will be needed.

**Comment by jessegreenberg** [comment]
I see, thanks for clarifying. I agree that tying to the puller index seems problematic for the reasons you described. And linking to the force is also problematic because it grows exponentially.

**Comment by jessegreenberg** [comment]
I created a linear mapping from force to shadow radius.  I changed the implementation so that there is only  one shadow that gets updated (rather than one for each image) which made it easier to mutate the shadow.

**Comment by jessegreenberg** [comment]
![capture](https://user-images.githubusercontent.com/6396244/29849576-fcce46ca-8ce4-11e7-9969-2d16f1eb50b9.PNG)

Looking good, we can tweak the shadow size if necessary at another time.
