### ISSUE TITLE
Arrow scaling for ISLC sims

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#21]
Continued discussion ffrom https://github.com/phetsims/coulombs-law/issues/27. We would like to discuss how arrow scaling should work for all sims that use this repo.

Initial questions:
- How should arrows look when they are really small? Can they disappear at really small values?
- Is it OK that at larger forces arrows go way off screen?
- Why was there some scaling for force arrows in GFL? At very small forces it looks like the arrows have zero length. But for some ranges, the arrows do not change in size.

**Comment by jessegreenberg** [comment]
Assigning to @arouinfar to consider or bring up for design discussion.

**Comment by arouinfar** [comment]
> How should arrows look when they are really small? Can they disappear at really small values?

I see two options here:

1. As F -> 0, arrow length -> 0. The force vectors for very small -- but non-zero -- forces will appear to be zero.
2. There is some minimum allowed length (such as the arrow tip), after which the vector does not shrink any further. However, if a F == 0 (meaning q = 0) the vector would still disappear.
![image](https://user-images.githubusercontent.com/8419308/34130918-ea556d2e-e406-11e7-8bd0-2797c3c18132.png)

I have a slight preference for option (1), as it may lead to some productive class discussions about scale/limiting behavior. However, I am fine with either approach, so long as the behavior is consistent across all ISLC sims.

> Is it OK that at larger forces arrows go way off screen?

In the extreme case, yes. We should optimize the scaling that <i>most</i> force vectors stay on-screen, but the largest forces can definitely go off-screen. 

> Why was there some scaling for force arrows in GFL? At very small forces it looks like the arrows have zero length. But for some ranges, the arrows do not change in size.

I was not a part of the original GFL team, so perhaps @ariel-phet has some insights. In Coulomb's Law, I prefer the look and feel of the non-Hollywooded vectors. [dev.6](https://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.6/coulombs-law_en.html) is linearly scaled, while [dev.7](https://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.7/coulombs-law_en.html) has some Hollywooding -- most noticeable on Atomic Scale screen. My guess is that allowing for a factor of 1000 difference between the two masses in GFL (instead of a factor of 10 in GFLB and CL) may have necessitated some Hollywooding. 

The scaling currently resides in `inverse-square-law-common` so the approach taken in CL would also apply to GFL and GFLB. If there were strong reasons to Hollywood the scaling in GFL, then we may need consider handling the scaling in the various sim repos -- though this is less maintainable.

@ariel-phet can you review and advise?

**Comment by jessegreenberg** [comment]
> I have a slight preference for option (1), as it may lead to some productive class discussions about scale/limiting behavior.

> I prefer the look and feel of the non-Hollywooded vectors.

I share the same preferences unless there is a reason to keep some portion of the arrow visible always.

**Comment by jessegreenberg** [comment]
After a slack discussion with  @arouinfar we decided to go ahead and remove the "hollywood" scaling in master so that we can see how changing this would impact GFL and GFL:B. That is done with the above commits.

**Comment by arouinfar** [comment]
On Slack @jessegreenberg said:
>  it looks like there is still a line in there that keeps the arrow tips visible in GFL and GF:B

Thanks for removing the Hollywooding on master @jessegreenberg! I think the vector scaling in GFL and GFLB looks and feels pretty good. I prefer how the arrow tips disappear in CL, but could live with them staying behind if others had a strong preference for that.

**Comment by jessegreenberg** [comment]
>  I prefer how the arrow tips disappear in CL.

I agree with this.

**Comment by ariel-phet** [comment]
@jessegreenberg @arouinfar - I don't remember why things were done a certain way (in terms of hollywooding for GFL), it could have been an MLL decision that we just never fixed, or vestigial from the original sim.

That being said, I think CL looks very good, and I like the way the arrow tips disappear in that one. Seems like that should be that strategy for all ISLC sims.

**Comment by jessegreenberg** [comment]
Great, thanks @arouinfar and @ariel-phet. @mbarlow12 could you work on this? I think this could be as easy as removing this line

```js
var minArrowLength = arrowForceRange.min === 0 ? 0 : 1;
```

but I haven't verified or tested.

**Comment by jessegreenberg** [comment]
@mbarlow12 I changed the behavior so we we could proceed with phetsims/gravity-force-lab-basics#22. Would you mind reviewing to see if there is anything else to do? I dont' think the change will have any impact on coulombs-law and everything tested OK, the impact should be for gravity-force-lab and gravity-force-lab basics.

**Comment by mbarlow12** [comment]
@arouinfar Do you have time tomorrow to go over the arrow scaling? The tweaks are quick to make, but it will likely be faster to sit down and hash it out than back and forth via github. Let @jessegreenberg or me know.  Thanks!

**Comment by arouinfar** [comment]
@mbarlow12 @jessegreenberg I'll be out of the office tomorrow, but could do a zoom chat before 11 am tomorrow. I'm also available after 3:00 this afternoon.

**Comment by jessegreenberg** [comment]
I am free tomorrow morning from 9am to 10:30am. I will likely be free this afternoon after 4pm.

**Comment by mbarlow12** [comment]
9am tomorrow works for me.

**Comment by jessegreenberg** [comment]
I believe we are OK with current behavior, can this be closed @arouinfar and @mbarlow12?

**Comment by mbarlow12** [comment]
I vote yes.

**Comment by arouinfar** [comment]
Agreed @mbarlow12.
