### ISSUE TITLE
ISLCModel.forceProperty  has a todo

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/inverse-square-law-common#38]
From #30, just marking this as an issue. `units` option for ForceProperty has this TODO:

> units: 'Newtons' // TODO: this appears unused in instance-proxies

@mbarlow12 and/or @samreid does this need to be addressed?

**Comment by samreid** [comment]
This issue is caused by https://github.com/phetsims/phet-io/issues/1292 -- inability to specify units or other NumberProperty metadata for DerivedProperties.  This doesn't need to be solved before 1.0, and I don't know how we'll proceed with https://github.com/phetsims/phet-io/issues/1292, but when I come up with a plan, I'll use this as a test case.

**Comment by jessegreenberg** [comment]
Thanks @samreid, in  that case marking as "deferred" for the 1.0 release.

**Comment by jessegreenberg** [comment]
Linking this issue to the TODO.

**Comment by samreid** [comment]
Addressed above, went through a medium-sized merge, @jessegreenberg can you check that nothing is disturbed?

**Comment by jessegreenberg** [comment]
Thanks @samreid. Removing deferred label. @mbarlow12 could you review the change?

**Comment by mbarlow12** [comment]
Reviewed. All sims seem to be running fine as well. Closing.
